version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/repo
    docker:
    # Primary container image where all steps run.
    - image: cimg/node:16.1.0
      auth:
        username: traian07 
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    #Secondary container image on common network.
    - image: circleci/postgres:9.6.2-alpine
      auth:
        username: traian07 
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      environment:
        POSTGRES_USER: postre
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: netflix
    
    steps:
      - checkout
      - run: npm -v
      - run: npm i
      #Wait for Postgres connection to open.
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: |
            npm run test